name: Ping Backend

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping Endpoint
        run: |
          curl -s -o /dev/null -w "%{http_code}" ${{ secrets.DOMAIN }}/ping
